messense/mupdf-rs

- src/display_list.rs
From [MuPDF Explored](https://ghostscript.com/~robin/mupdf_explored.pdf):
> Once displaylists  are  created  from  that  document,  multiple  threads  can  operate  on them safely.
Think this should be safe.
> Implement Send/Sync for DisplayList

- Cargo.toml
- mupdf-sys/Cargo.toml
- mupdf-sys/build.rs
Adds features to the `mupdf-sys` crate which map to some of the options in [fitz/config.h](https://github.com/ArtifexSoftware/mupdf/blob/master/include/mupdf/fitz/config.h).
Of course, more or all of the options could be added as features if deemed necessary; I found these to be the most effective in reducing the size of the library.
> build: use features to control build configuration

- src/document.rs
I noticed that calling `metadata(MetadataName::Title)` title always returned an empty string, even when the document does have a title set. This change corrects that.
> Correct c_key string for Title metadata

- src/pdf/filter.rs
Fix two sources UB:
1. A double free of the image which gets passed image_filter_callback().
Mupdf retains ownership of the image so we mustn't drop it. This
fixes test_filters.rs.
2. The callback wrapper's lifetime is now properly tracked by the
PdfFilterOptions struct. While this isn't required to fix the test
it is a correctness fix and now passes miri validation. See [1] for
a minimized comparison between three different approaches for this
problem.
[1]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=02fb40ba51deac47eb3e1960cb6e787d
Somewhat amusingly number 1 is what I spotted immediately and is sufficient for the test to pass. But since I was already running with address sanitizer it still complained so I went down the rabbit hole for number 2 which was much …
> Fix undefined behavior in PDF image filtering

- .github/workflows/CI.yml
- src/text_page.rs
- tests/test_issues.rs
The first commit adds a Address Sanitizer job to our CI. See https://github.com/Bobo1239/mupdf-rs/runs/3329570361?check_suite_focus=true#step:4:230 for how the address sanitizer detected #27.
The second commit fixes the bug by tracking the necessary lifetimes and making the code from the issue uncompilable without modifications.
> Add address sanitizer CI job & fix #27

- mupdf-sys/build.rs
Otherwise the build fails with linker errors at the end and no clue that MuPDF was never built.
> Panic if devenv couldn't be found

- Cargo.toml
- src/context.rs
- src/lib.rs
When cross-compiling, including font-kit complicates the build process
significantly and loading system fonts is not always required.
> Make loading system fonts dependent on `system-fonts` feature

- Cargo.toml
- examples/extract_stext.rs
- mupdf-sys/wrapper.c
- src/page.rs
- src/text_page.rs
works exactly the same as toStructuredText
https://mupdf.readthedocs.io/en/latest/mupdf-js.html#toStructuredText,
but the disadvantage is that mupdf first has to create json, and then
mupdf-rs is already parsing it, but the result corresponds to the output of toStructuredText
I would like this functionality to be included in the release
> added functionality for receiving and parsing stext from page

- src/document.rs
- src/page.rs
Clone trait was implemented for Page and Document structs in `src/page.rs` and `src/document.rs` using `fz_keep_page` and `fz_keep_document` methods which increment's MuPDF's internal reference count for the target structures.
Otherwise no major changes were made. All tests are passing.
Have a great day!
> Clone traits implemented

- mupdf-sys/wrapper.c
- src/destination.rs
- src/lib.rs
- src/pdf/document.rs
- src/pdf/object.rs
- src/point.rs
Resolve https://github.com/messense/mupdf-rs/issues/54 .
> Set outlines of PDF

- .github/workflows/CI.yml
- mupdf-sys/build.rs
Introducing support for the MSYS2 build environment. This addition addresses the licensing challenges faced by enterprises when using the MSVC build on Windows. Additionally, it resolves issues related to path separators.
> Add support for msys2 environment

- .github/workflows/CI.yml
- mupdf-sys/build.rs
update CI and fix build bug on gnu environment
> fix build script on gnu environment

- src/font.rs
The `outline_glyph` and `outline_glyph_with_ctm` functions returned a `Path` containing a null pointer in case a glyph was unable to be outlined.
`fz_outline_glpyh` tries to avoid throwing errors, does however throw one in case allocation fails. I'm not sure if i should keep the Result for that case.
> Return an Option from `outline_glyph` instead of a `Path` containing a null pointer

- mupdf-sys/wrapper.c
- src/path.rs
This removes the creation of a vtable optional for `PathWalker` by making the `Path::walk` method generic over `PathWalker`. As `PathWalker` is implemented for all `&mut PathWalker` passing `&mut PathWalker` or `&mut dyn PathWalker` to the `walk` method is still possible.
It also adds the optional `curve_to_y` and `rect` methods to the trait that default to calling the methods that mupdf would call as well if the function pointers in the `fz_path_walker` struct were `None`. This can sadly not be done for `curve_to_v` and `quad_to` as both of them require knowledge of the start position to call the default, which is not available to as as the trait.
This also changes the parameter type of the `Path::rect` function from `i32` to `f32` as this is what the C API seems to pass to us.
> Allows `PathWalker` to be used without creating a vtable

- src/color_params.rs
Shrinks `ColorParams` size from an `i32` down to a `u8` using a bitflag approach. Imagining the u8 byte as a array of bits the layout looks like this: `[0, 0, 0, opm, op, bp, ri, ri]`.
This also implements `From<fz_color_params>` and adds a Debug implementation that displays the `ColorParams` as a struct: `ColorParams { rendering_intent: Saturation, bp: true, op: false, opm: false }` for the result of `ColorParams::new(RenderingIntent::Saturation, true, false, false)`.
> Rework `ColorParams` internals and allow conversion from `fz_color_params`

- mupdf-sys/wrapper.c
- src/colorspace.rs
This add the `convert_color` and `convert_color_into` methods to `Colorspace`, allowing you to convert colors between colorspaces into a `Vec<f32>` or a `&mut [f32]`. It asserts whether the input or output is long enough to ensure no out of bounds reads or writes.
> Add `convert_color` to `Colorspace`

- mupdf-sys/Cargo.toml
- mupdf-sys/build.rs
Parses the mupdf docs and converts them into a more docs.rs friendly format. It links other types and functions and puts some parameter names in markdown inline code apostrophes. It also escapes `<`, `>`, `[` and `]` as docs.rs will interpret them as HTML or links otherwise, causing the `<path>` tag to disappear as in the pink highlighted example below.
It also splits at every linebreak, which sometimes looks a bit unnecessary, but cases like the last example from the table below are otherwise unreadable.
Because of the very different styles of comments across the mupdf codebase some weird formatting issues might happen with this change, but I've looked for these cases and haven't found any yet.
Here are some comparisons:
Before            | After …
> Improve `mupdf-sys` docs

- .github/workflows/CI.yml
- src/buffer.rs
- src/context.rs
- src/device.rs
- src/document.rs
- src/error.rs
- src/pdf/document.rs
- src/pdf/object.rs
- src/stroke_state.rs
- src/system_font.rs
- src/text.rs
Just ran `cargo clippy --tests` and applied the fixes, essentially. Also changed `cargo check` in CI to run clippy instead and error if it produces any warnings.
> Apply cleanups suggested by clippy and plug it into CI

- .github/workflows/CI.yml
- Cargo.toml
- src/page.rs
`serde`'s functionality isn't needed to make this library work and, imo, should be moved to sit behind a feature flag so that those who don't need it don't have to wait for the `derive(Serialize, Deserialize)` to run.
Also, `serde_json` isn't used at all in the main library outside of tests and examples, so I moved it `dev_dependencies`
> Make serde optional and move serde_json into dev-dependencies

- .github/workflows/CI.yml
- Cargo.toml
- mupdf-sys/Cargo.toml
- mupdf-sys/build.rs
- src/array.rs
- src/document.rs
- src/error.rs
- src/lib.rs
- src/page.rs
- src/pdf/document.rs
- src/pdf/page.rs
- src/point.rs
- src/quad.rs
- src/text_page.rs
This is a kinda gnarly PR, and I honestly don't expect it to go through 100% as-is since it's quite opinionated.
The main things it does are:
1. Introduces `zerocopy` as a dependency so that we can use their `IntoBytes` & `FromBytes` traits along with the `transmute!` macro to make some conversions zero-cost.
2. Introduces two more traits, `FFIAnalogue` and `FFIWrapper` to implement for rust types which mirror or wrap FFI types (e.g. `FFIAnalogue` for when something has the same fields as the FFI type and `FFIWrapper` when it just contains a pointer to the `FFI` type). These, along with macros to implement them, allow us deduplicate a lot of code (e.g. `Drop` impls, get rid of a lot of `unsafe { *self.inner }.whatever` and just use `self.as_ref().whatever` instead)
3. Change a lot of …
> Overhaul many parts of unsafe semantics using zerocopy and NonNulls

- mupdf-sys/build.rs
- mupdf-sys/src/lib.rs
- mupdf-sys/wrapper.c
- src/device.rs
- src/device/custom.rs
- src/device/native.rs
- src/lib.rs
This allows creating `Device`s in Rust by implementing the `NativeDevice` trait and calling the `Device::from_native()` function.
> Add the ability to write `Device`s in Rust

- src/bitmap.rs
- src/buffer.rs
- src/colorspace.rs
- src/cookie.rs
- src/device.rs
- src/device/native.rs
- src/display_list.rs
- src/document.rs
- src/document_writer.rs
- src/error.rs
- src/font.rs
- src/image.rs
- src/page.rs
- src/path.rs
- src/pdf/annotation.rs
- src/pdf/document.rs
- src/pdf/graft_map.rs
- src/pdf/object.rs
- src/pdf/page.rs
- src/pixmap.rs
- src/rect.rs
- src/stroke_state.rs
- src/text.rs
- src/text_page.rs
This allows us to remove a lot of eyes of sauron (`Ok(())`) and just clean a lot of stuff up, generally
This also helps with some more work I'd like to do related to #109 (specifically in enabling `clippy::multiple_unsafe_ops_per_block`).
> Don't short-circuit in ffi_try

- src/array.rs
I just noticed I missed this when I first added the implementation for FzArray.
> Impl Send + Sync for FzArray

- mupdf-sys/build.rs
Hello, I noticed that with `cargo build --all-features`, `pkg-config` can't find the tesseract library. Here's a small change to fix this.
> Fix typo in the `sys-lib-tesseract` feature

- mupdf-sys/wrapper.c
- src/document.rs
- src/page.rs
- tests/test_issues.rs
- mupdf expects alpha to be a bool signifying whether to apply alpha
- mupdf can accept paths that can be opened by `open(2)` per 12.2 https://ghostscript.com/~robin/mupdf_explored.pdf#page=83
> make corrections

- src/document.rs
- src/error.rs
- src/file_path.rs
- src/lib.rs
- tests/test_issues.rs
This creates a `FilePath` newtype, as mupdf requires paths to be UTF-8 on windows.
It supports `AsRef`ing from:
- `str` on all platforms
- `[u8]` on all platforms, but windows
- `OsStr` and `Path` on unix and wasi
On top of that `Debug` is implemented and  `TryFrom` is implemented for `OsStr` and `Path`.
Thanks to @kirawi for discovering this limitation of mupdf and implementing it in mupdf-rs in #122.
> Add FilePath newtype

- .github/workflows/CI.yml
- mupdf-sys/build.rs
This PR fixes the problem (#138) of building mupdf with visual studio 2022 which is part of the windows-2022 and windows-2025 github runners.
> Fix build on windows-2022 and windows-2025 (visual studio 2022)

- .github/workflows/CI.yml
- Cargo.toml
- mupdf-sys/Cargo.toml
- mupdf-sys/build.rs
- mupdf-sys/docs.rs
- mupdf-sys/make.rs
- mupdf-sys/msbuild.rs
- src/buffer.rs
- src/context.rs
- src/display_list.rs
- src/document.rs
- src/lib.rs
- src/page.rs
- src/pdf/document.rs
- src/pdf/object.rs
- src/pdf/page.rs
- src/text_page.rs
- tests/test_issues.rs
Maybe in the future, just improved copy for now
> Refactor mupdf-sys build script

- mupdf-sys/wrapper.c
- src/destination.rs
- src/document.rs
- src/link.rs
- src/outline.rs
- src/page.rs
- src/pdf/document.rs
- src/rect.rs
Fix #68 by providing more information inside `Outline` by using the new `LinkDestination` struct and adding `page_number` to `Location` (which is what #68 is looking for).
The naming isn't great as there is `page` and `page_number` but i couldn't come up with anything better and that is what mupdf calls them themselves. I added a doc comment to clarify things. If somebody has a better idea for a name I would be more than welcome to change it.
This changes the output of `.outlines()` on a from, for example
```rust
Outline {
title: "Copyright",
uri: None,
page: Some(
0,
),
down: [],
x: 0.0,
y: 0.0,
}
```
to
```rust
Outline {
title: "Copyright",
uri: Some(
"OEBPS/Text/copyright.xhtml",
),
dest: Some(
LinkDestination {
loc: Location {
chapter: 23,
page: 0,
page_number: 186,
},
kind: XYZ { …
```
> Return more information for `outlines`

- .github/workflows/CI.yml
It's deprecated and causes #148 and #149 CI runs to fail
> Remove windows 2019 from CI

- mupdf-sys/build.rs
- mupdf-sys/make.rs
- mupdf-sys/src/lib.rs
- mupdf-sys/wrapper.c
This makes functions and types specified as internal not show up in the bindings. On top it also only exports the needed C std types and makes them opaque.
Before
After
The harfbuzz cc flag fixes an error that occurs on my machine when cross compiling to windows (the harfbuzz-sys crate also has this flag set).
> Remove bindings to private or c std types

- Cargo.toml
- src/device.rs
- src/device/native.rs
- src/error.rs
- src/font.rs
- src/lib.rs
- src/pdf/annotation.rs
- src/pdf/document.rs
- src/stroke_state.rs
- src/system_font.rs
- src/text.rs
- src/text_page.rs
This replaces the `num_enum::TryFromPrimitive` macro with a small declarative macro, allowing to remove the dependency on `num_enum` (which depends on `toml-edit` for example).
> Get rid of num_enum dependency

- src/colorspace.rs
- src/error.rs
- src/pdf/object.rs
- tests/test_issues.rs
Applies the now warn-by-default [`uninlined_format_args`](https://rust-lang.github.io/rust-clippy/stable/index.html?groups=style#uninlined_format_args) clippy lint in some places were it was still missing.
> Fix 1.88 clippy complaints

- src/device/native.rs
> Fix memory safety of native device

- .github/workflows/CI.yml
- Cargo.toml
- src/buffer.rs
- src/color.rs
- src/colorspace.rs
- src/device.rs
- src/device/native.rs
- src/lib.rs
- src/pdf/annotation.rs
- src/pdf/document.rs
Clippy was complaining about some missing `Default` impls, and I also noticed that some doc links were broken so I added a `cargo doc` call to CI
> Fix some clippy and doc issues and add docs to CI
